services:
  api:
    container_name: social_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - social_node_modules:/app/node_modules
    command: npm run dev

  postgres:
    image: postgres:16
    container_name: social_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_db
    ports:
      - "5432:5432"
    volumes:
      - social_pgdata:/var/lib/postgresql/data

volumes:
  social_node_modules:
  social_pgdata:
